# Generated by Django 3.2.9 on 2022-04-07 07:13

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Category name')),
                ('slug', models.SlugField(max_length=512, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('message', models.CharField(max_length=100, verbose_name='Message')),
                ('message_uz', models.CharField(max_length=100, null=True, verbose_name='Message')),
                ('message_ru', models.CharField(max_length=100, null=True, verbose_name='Message')),
                ('message_en', models.CharField(max_length=100, null=True, verbose_name='Message')),
                ('message_long', models.TextField(verbose_name='Message long')),
                ('message_long_uz', models.TextField(null=True, verbose_name='Message long')),
                ('message_long_ru', models.TextField(null=True, verbose_name='Message long')),
                ('message_long_en', models.TextField(null=True, verbose_name='Message long')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
            },
        ),
        migrations.CreateModel(
            name='Managment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='F.I.SH')),
                ('name_uz', models.CharField(max_length=250, null=True, verbose_name='F.I.SH')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='F.I.SH')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='F.I.SH')),
                ('title', models.CharField(max_length=250, verbose_name='Lavozimi')),
                ('title_uz', models.CharField(max_length=250, null=True, verbose_name='Lavozimi')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='Lavozimi')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='Lavozimi')),
                ('slug', models.SlugField(max_length=512, unique=True)),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('acceptance_dates', models.CharField(max_length=250, verbose_name='Qabul kunlari')),
                ('biography', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tarjimai hol')),
                ('biography_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tarjimai hol')),
                ('biography_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tarjimai hol')),
                ('biography_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tarjimai hol')),
                ('functions_tasks', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Funksiya va vazifalar')),
                ('functions_tasks_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Funksiya va vazifalar')),
                ('functions_tasks_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Funksiya va vazifalar')),
                ('functions_tasks_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Funksiya va vazifalar')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Rahbaryat',
                'verbose_name_plural': 'Rahbaryat azolari',
            },
        ),
        migrations.CreateModel(
            name='Media_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media turi',
                'verbose_name_plural': 'Media turlari',
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MenuCategoriya',
                'verbose_name_plural': 'MenuCategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='RegionalCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Hududiy boshqarma nomi')),
                ('name_uz', models.CharField(max_length=250, null=True, verbose_name='Hududiy boshqarma nomi')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='Hududiy boshqarma nomi')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='Hududiy boshqarma nomi')),
                ('leader', models.CharField(max_length=250, verbose_name="F.I.SH BOshqarma boshlig'i")),
                ('leader_uz', models.CharField(max_length=250, null=True, verbose_name="F.I.SH BOshqarma boshlig'i")),
                ('leader_ru', models.CharField(max_length=250, null=True, verbose_name="F.I.SH BOshqarma boshlig'i")),
                ('leader_en', models.CharField(max_length=250, null=True, verbose_name="F.I.SH BOshqarma boshlig'i")),
                ('title', models.CharField(max_length=250, verbose_name='Manzili')),
                ('title_uz', models.CharField(max_length=250, null=True, verbose_name='Manzili')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='Manzili')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='Manzili')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Hududiy bo'lim",
                'verbose_name_plural': "Hududiy bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='F.I.SH')),
                ('name_uz', models.CharField(max_length=250, null=True, verbose_name='F.I.SH')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='F.I.SH')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='F.I.SH')),
                ('title', models.CharField(max_length=250, verbose_name='Lavozimi')),
                ('title_uz', models.CharField(max_length=250, null=True, verbose_name='Lavozimi')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='Lavozimi')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='Lavozimi')),
                ('slug', models.SlugField(max_length=512, unique=True)),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('acceptance_dates', models.CharField(max_length=250, verbose_name='Qabul kunlari')),
                ('biography', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tarjimai hol')),
                ('biography_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tarjimai hol')),
                ('biography_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tarjimai hol')),
                ('biography_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tarjimai hol')),
                ('functions_tasks', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Funksiya va vazifalar')),
                ('functions_tasks_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Funksiya va vazifalar')),
                ('functions_tasks_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Funksiya va vazifalar')),
                ('functions_tasks_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Funksiya va vazifalar')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Hokimlik aparati',
                'verbose_name_plural': 'Hokimlik aparatlari',
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Qisqa matn')),
                ('title_uz', models.CharField(max_length=300, null=True, verbose_name='Qisqa matn')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Qisqa matn')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Qisqa matn')),
                ('slug', models.SlugField(max_length=512, unique=True)),
                ('Text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('Text_uz', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('Text_ru', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('Text_en', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Qisqa matn')),
                ('title_uz', models.CharField(max_length=300, null=True, verbose_name='Qisqa matn')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Qisqa matn')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Qisqa matn')),
                ('slug', models.SlugField(max_length=512, unique=True)),
                ('Text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('Text_uz', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('Text_ru', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('Text_en', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=512, unique=True)),
                ('body', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('fiel_name', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Media')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.media_type', verbose_name='Media nomi')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medialar',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('fiel_name', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Files')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.menucategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Bolim',
                'verbose_name_plural': 'Bolimlar',
            },
        ),
        migrations.CreateModel(
            name='FaieldFiled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Doc name')),
                ('name_uz', models.CharField(max_length=250, null=True, verbose_name='Doc name')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='Doc name')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='Doc name')),
                ('slug', models.SlugField(max_length=512, unique=True)),
                ('fiel_name', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Fiels')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('categor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.categorydoc')),
                ('categor_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.categorydoc')),
                ('categor_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.categorydoc')),
                ('categor_uz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.categorydoc')),
            ],
        ),
    ]
