# Generated by Django 3.2.9 on 2022-04-07 07:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='media',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Text_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Text_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
