# Generated by Django 3.2.9 on 2022-09-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='fiel_name',
            field=models.FileField(default=1, upload_to='documents/%Y/%m/%d/', verbose_name='Media yuklash shart'),
            preserve_default=False,
        ),
    ]
