# Generated by Django 3.2.9 on 2022-11-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20220917_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorydoc',
            options={'verbose_name': 'Xujjat  TURI', 'verbose_name_plural': 'Xujjatlar  TURLARI'},
        ),
        migrations.AlterModelOptions(
            name='faieldfiled',
            options={'verbose_name': 'Xujjat BAZASI', 'verbose_name_plural': 'Xujjatlar BAZASI'},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': "Menyu BO'LIM", 'verbose_name_plural': "Menyu BO'LIMLAR"},
        ),
        migrations.AlterModelOptions(
            name='managment',
            options={'verbose_name': 'Rahbaryat  AZOSI', 'verbose_name_plural': 'Rahbaryat  AZOLARI'},
        ),
        migrations.AlterModelOptions(
            name='media_type',
            options={'verbose_name': 'Media TURI', 'verbose_name_plural': 'Media TURLARI'},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name': 'Menyu  KATEGORYA', 'verbose_name_plural': 'Menyu  KATEGORYALAR'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Matbuot  YANGILIK', 'verbose_name_plural': 'Matbuot  YANGILIKLAR'},
        ),
        migrations.AlterModelOptions(
            name='poster',
            options={'verbose_name': "Matbuot  E'LONLAR", 'verbose_name_plural': "Matbuot  E'LONLAR"},
        ),
        migrations.AlterModelOptions(
            name='regionalcenters',
            options={'verbose_name': "Hududiy  BO'LIM", 'verbose_name_plural': "Hududiy  BO'LIMLAR"},
        ),
        migrations.AlterModelOptions(
            name='sections',
            options={'verbose_name': 'Rahbaryat  XODIM', 'verbose_name_plural': 'Rahbaryat XODIMLAR'},
        ),
    ]
